# Generated by Django 6.0.2 on 2026-03-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Recognotion",
            new_name="Recognition",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="status",
        ),
    ]
