# Generated by Django 6.0.3 on 2026-04-04 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="visit_id",
        ),
        migrations.AddField(
            model_name="visit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vms.volunteerschedule",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerabsence",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="volunteerabsence",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
