# Generated by Django 6.0.3 on 2026-10-06 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence', models.CharField(choices=[('NONE', 'One time'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 weeks')], default='NONE', max_length=8)),
                ('dayofweek', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('volunteers_needed', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms.volunteeringpreference')),
                ('required_languages', models.ManyToManyField(blank=True, to='vms.language')),
                ('required_skills', models.ManyToManyField(blank=True, to='vms.skill')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='vms.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunitySignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WITHDRAWN', 'Withdrawn by volunteer'), ('REMOVED', 'Removed by coordinator')], default='ACCEPTED', max_length=9)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=255)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_signups', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='vms.opportunityshift')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_signup', to='vms.visit')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_signups', to='vms.volunteer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='opp_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='opp_end_date_after_start'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('volunteers_needed__gte', 1)), name='opp_needs_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='opportunityshift',
            constraint=models.UniqueConstraint(fields=('opportunity', 'shift_date'), name='uniq_shift_per_day'),
        ),
        migrations.AddConstraint(
            model_name='opportunitysignup',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('shift', 'volunteer'), name='uniq_active_signup'),
        ),
    ]
